### ISSUE TITLE
你那个颜色板点击没用啊，改不了颜色

### ISSUE THREAD

**Issue by zhangdongpo** [CaffreySun/CFYNavigationBarTransition#1]

**Comment by CaffreySun** [comment]
ViewController.m文件第27行[self.navigationController closeCFYNavigationBarFunction:YES];
改为：
[self.navigationController closeCFYNavigationBarFunction:NO];
这里为"YES"代表对当前navigationController关闭这个库提供的功能了
这么做的原因是，有些系统提供的navigationController加上了本库后，会很奇怪

**Comment by CaffreySun** [comment]
已更新代码，将ViewController.m文件第27行[self.navigationController closeCFYNavigationBarFunction:YES];注释掉了，demo可以直接用了
