### ISSUE TITLE
更改color不是针对单独的viewController?

### ISSUE THREAD

**Issue by zhongwen42** [CaffreySun/CFYNavigationBarTransition#3]
cfy_setNavigationBarBackgroundColor 更改往后所有的viewController的navigationbar的颜色吗

**Comment by CaffreySun** [comment]
是这样，如果当前viewController修改了navigationbar颜色，但是push出的VC没有修改navigationbar颜色，那么push出的VC将会使用上一个VC的navigationbar的颜色
