### ISSUE TITLE
状态栏透明的问题

### ISSUE THREAD

**Issue by jHonwAll** [CaffreySun/CFYNavigationBarTransition#4]
最近发现一个问题：
用这个库，跟MJRefresh控件一起用，做了一个导航栏从透明渐变为黑色的效果。但是，偶尔会出现状态栏透明之后，不随着导航栏颜色改变，一直保持透明。这个是跟MJRefresh有啥冲突吗？
有个规律，MJRefresh控件设置mj_footer，而且tableView有分页的时候，就会出现这种情况。我手动替换掉mj_footer之后，以为解决问题了。但是，在iPhone 5s上还是会偶现这个问题。

**Comment by CaffreySun** [comment]
请问你用的是UITableViewController还是UIViewController上增加TableView

**Comment by CaffreySun** [comment]
@jHonwAll 我尝试使用MJRefresh做分页和渐变时，没有发现出现状态栏的问题。有可以复现的demo吗？

**Comment by jHonwAll** [comment]
木有demo额(⊙o⊙)…
页面实现步骤就是：
1，进入页面，设置 [self cfy_setNavigationBarAlpha:0.0];
2，请求页面数据，每页显示20条，用MJRefresh来实现上拉加载下一页的数据；
3，拉倒底部的时候，当请求完所有数据，会设置一个footer，代码如下
-(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section
{
    if (section == 3&&_isDataFinished) {
        NSArray *arr = [[NSBundle mainBundle]loadNibNamed:@"CFBottomFooterView" owner:nil options:nil];
        UIView *footerView = [arr firstObject];
        return footerView;
    }else{
        return nil;
    }
}

当页数大于一页的时候（也就是我手动添加的footer没有显示在页面的时候），会出现我所描述的情况。

**Comment by CaffreySun** [comment]
@jHonwAll 现在只在5S上回出现？手机系统多少？

**Comment by CaffreySun** [comment]
总结一下调查结果：当UIViewController的edgesForExtendedLayout赋值为非UIRectEdgeTop时(UIRectEdgeAll是包括了UIRectEdgeTop)，在UIViewController的viewWillLayoutSubviews获取到的导航栏高度不正常，缺少了状态栏高度。
但当代码指定到UINavigationController的viewWillLayoutSubviews时，获取到的导航栏高度为正常高度。
所以在UINavigationController的viewWillLayoutSubviews方法里手动调用一下UIViewController的viewWillLayoutSubviews方法，来重新获取导航栏高度。

这个问题将会在版本1.2.2修复
