### ISSUE TITLE
关于导航栏消失的问题

### ISSUE THREAD

**Issue by kegan23** [CaffreySun/CFYNavigationBarTransition#6]
你好，最近发现一个问题，在有导航栏的视图准备presentViewController的时候，使用如下代码会导致动画过程中导航栏突然消失。

present的代码如下：
- (void)present {
    UIViewController *vc = [self getViewControllerToPresent];
    [UIView animateWithDuration:0.7 animations:^{
        self.view.transform = CGAffineTransformScale(self.view.transform, 0.9, 0.9);
    }];
    [self presentViewController:vc animated:YES completion:nil];
}

**Comment by CaffreySun** [comment]
[UIView animateWithDuration:0.7 animations:^{
self.view.transform = CGAffineTransformScale(self.view.transform, 0.9, 0.9);
}];
这么做的目的是为了实现专场动画吗？

**Comment by kegan23** [comment]
是的，执行这个动画的时候导航栏就消失了。

**Comment by CaffreySun** [comment]
@kegan23 我更新了一下(版本1.3.1)，优化了导航栏位置计算，你试试能不能满足你的需求

**Comment by CaffreySun** [comment]
给你推荐另一个库吧[NNNavigationBar](https://github.com/amisare/NNNavigationBar) 看看这个能不能满足你的需求
